//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int ID { get; set; }
        public string MotivoDeSalida { get; set; }
        public Nullable<System.DateTime> fechaVisita { get; set; }
        public Nullable<System.TimeSpan> horaEntrada { get; set; }
        public Nullable<System.TimeSpan> horaSalida { get; set; }
        public string Nombre { get; set; }
        public string ContactoQuienLoRecibio { get; set; }
    }
}
